added safety checks

diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -1,10 +1,41 @@
 #!/usr/bin/env bash
 
-echo "Hello"
+if [[ $# -eq 0 ]]
+then
+    echo "ERROR: No input CSV file provided" >&2
+    exit 1
+fi
+
+if [[ ! -f "$1" ]]
+then
+    echo "ERROR: Input file not found in the current
+directory" >&2
+    exit 1
+fi
+
+if [[ "$1" != *.csv ]]
+then
+    echo "ERROR: Input file expected in a CSV format" >&2
+    exit 1
+fi
+
+if [[ ! -s "$1" ]]
+then
+    echo "ERROR: Empty file provided" >&2
+    exit 1
+fi
+
+num_cols=$(gawk -F',' 'NR==1 { print NF }' "$1")
+
+if [[ "$num_cols" -ne 7 ]]
+then
+    echo "ERROR: Expected 7 columns in the input" >&2
+    exit 1
+fi
+
 
 gawk -F ',' '
 BEGIN {
-    print "hola"
     count = 0
 }
 NR==1 {
@@ -41,12 +72,11 @@ NR==1 {
 NR>1 {
     #key_array
     #value_array
-    #print "test"
     if(NF == header_cell_count) {
         if(length($1) > 0 && length($2) > 0 && length($3) > 0 && length($4) > 0 && length($5) > 0 && length($6) > 0) {
-            #count++
+            
             if($4 > 0 && $5 > 0) {
-                #count++
+                
                 time_val = substr($2, 1, 10)
                 row_val = $1 "," time_val "," $3
                 row_val = row_val "," $4 "," $5 "," $6
@@ -58,11 +88,12 @@ NR>1 {
                     count++
                 }
             }
-            #print "empty video id"
+            
         } 
     }
 }
 END{
-    print count
+    exit 0
+    #print count
     #print value_array > 
-}' trending_videos_unclean.csv
+}' "$1"
